# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1508721051);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1508721291);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1508721171);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.slowStartup.averageTime", 4070);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20141013200408");
user_pref("browser.startup.homepage_override.mstone", "33.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1508807331342");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1508720931342");
user_pref("datareporting.sessions.current.activeTicks", 10);
user_pref("datareporting.sessions.current.firstPaint", 3793);
user_pref("datareporting.sessions.current.main", 880);
user_pref("datareporting.sessions.current.sessionRestored", 4107);
user_pref("datareporting.sessions.current.startTime", "1508720929070");
user_pref("datareporting.sessions.current.totalTime", 195);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-ja@firefox.mozilla.org\":{\"version\":\"33.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ja@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:33.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1386716963000,\"rdfTime\":1375741724000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1416202190000,\"rdfTime\":1413232571000},\"langpack-ja@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ja@firefox.mozilla.org.xpi\",\"mtime\":1413234048000}}}]");
user_pref("extensions.lastAppVersion", "33.0");
user_pref("extensions.lastPlatformVersion", "33.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20141013200408");
user_pref("gecko.mstone", "33.0");
user_pref("idle.lastDailyNotification", 1508721297);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1508720995);
user_pref("media.gmp-gmpopenh264.version", "1.1");
user_pref("media.gmp-manager.lastCheck", 1508720994);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 102484);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1508720929);
user_pref("toolkit.telemetry.previousBuildID", "20141013200408");
